public class Strings {
    public static void main(String[] args) {
        String str = "Hello, World!";
        System.out.println(str.length());
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello, World!");
        str.equalsIgnoreCase("Hello, World!");
        str.startsWith("Hello");
        str.endsWith("World!");
        str.contains("World");
        str.isEmpty();
        str.length();
        str.charAt(0);
        str.substring(0, 5);
        str.indexOf("World");
        str.replace("World", "Java");
        str.toLowerCase();
        str.toUpperCase();
        str.trim();
        str.equals("Hello");
        System.out.println(str.length());
        System.out.println(str.charAt(0));
        System.out.println(str.substring(0, 5));
        System.out.println(str.indexOf("World"));
        System.out.println(str.replace("World", "Java"));
        System.out.println(str.toLowerCase());
        System.out.println(str.toUpperCase());
        System.out.println(str.trim());
        System.out.println(str.equals("Hello, World!"));
        System.out.println(str.equalsIgnoreCase("Hello, World!"));
        System.out.println(str.startsWith("Hello"));
        System.out.println(str.endsWith("World!"));
        System.out.println(str.contains("World"));
        System.out.println(str.isEmpty());
        System.out.println(str.length());
        System.out.println(str.charAt(0));
        System.out.println(str.substring(0, 5));
        System.out.println(str.indexOf("World"));
        System.out.println(str.replace("World", "Java"));
        System.out.println(str.toLowerCase());
        System.out.println(str.toUpperCase());
        System.out.println(str.trim());
        System.out.println(str.equals("Hello, World!"));
        System.out.println(str.equalsIgnoreCase("Hello, World!"));
        System.out.println(str.startsWith("Hello"));
        System.out.println(str.endsWith("World!"));
        System.out.println(str.contains("World"));
        System.out.println(str.isEmpty());
        System.out.println(str.length());
        System.out.println(str.charAt(0));
        System.out.println(str.substring(0, 5));
        System.out.println(str.indexOf("World"));
        System.out.println(str.replace("World", "Java"));
        System.out.println(str.toLowerCase());
        System.out.println(str.toUpperCase());
        System.out.println(str.trim());
        System.out.println(str.equals("Hello, World!"));
        System.out.println(str.equalsIgnoreCase("Hello, World!"));
        System.out.println(str.startsWith("Hello"));
        System.out.println(str.endsWith("World!"));
        System.out.println(str.contains("World"));
        System.out.println(str.isEmpty());
        System.out.println(str.length());
        System.out.println(str.charAt(0));
        System.out.println(str.substring(0, 5));
        System.out.println(str.indexOf("World"));
        System.out.println(str.replace("World", "Java"));
        System.out.println(str.toLowerCase());
        System.out.println(str.toUpperCase());
        System.out.println(str.trim());
        System.out.println(str.equals("Hello, World!"));
        System.out.println(str.equalsIgnoreCase("Hello, World!"));
        System.out.println(str.startsWith("Hello"));
        System.out.println(str.endsWith("World!"));
        System.out.println(str.contains("World"));
        System.out.println(str.isEmpty());
        System.out.println(str.length());
        System.out.println(str.charAt(0));
        System.out.println(str.substring(0, 5));
        System.out.println(str.indexOf("World"));
        System.out.println(str.replace("World", "Java"));
        System.out.println(str.toLowerCase());
        System.out.println(str.toUpperCase());
        System.out.println(str.trim());
        System.out.println(str.equals("Hello, World!"));
        System.out.println(str.equalsIgnoreCase("Hello, World!"));
        System.out.println(str.startsWith("Hello"));
        System.out.println(str.endsWith("World!"));
        System.out.println(str.contains("World"));
        System.out.println(str.isEmpty());
        System.out.println(str.length());
        System.out.println(str.charAt(0));
        System.out.println(str.substring(0, 5));
        System.out.println(str.indexOf("World"));
        System.out.println(str.replace("World", "Java"));
        System.out.println(str.toLowerCase());
        System.out.println(str.toUpperCase());
        System.out.println(str.trim());
        System.out.println(str.equals("Hello, World!"));
        System.out.println(str.equalsIgnoreCase("Hello, World!"));
        System.out.println(str.startsWith("Hello"));
        System.out.println(str.endsWith("World!"));
        System.out.println(str.contains("World"));
        System.out.println(str.isEmpty());
        System.out.println(str.length());
        System.out.println(str.charAt(0));
        System.out.println(str.substring(0, 5));
        System.out.println(str.indexOf("World"));
        System.out.println(str.replace("World", "Java"));
        System.out.println(str.toLowerCase());
        System.out.println(str.toUpperCase());
        System.out.println(str.trim());
        System.out.println(str.equals("Hello, World!"));
        System.out.println(str.equalsIgnoreCase("Hello, World!"));
        System.out.println(str.startsWith("Hello"));
        System.out.println(str.endsWith("World!"));
        System.out.println(str.contains("World"));
        System.out.println(str.isEmpty());
        System.out.println(str.length());
        System.out.println(str.charAt(0));
        System.out.println(str.substring(0, 5));
        System.out.println(str.indexOf("World"));
        System.out.println(str.replace("World", "Java"));
        System.out.println(str.toLowerCase());
        System.out.println(str.toUpperCase());
        System.out.println(str.trim());
        System.out.println(str.equals("Hello, World!"));
        System.out.println(str.equalsIgnoreCase("Hello, World!"));
        System.out.println(str.startsWith("Hello"));
        System.out.println(str.endsWith("World!"));
        System.out.println(str.contains("World"));
        System.out.println(str.isEmpty());
        System.out.println(str.length());
        System.out.println(str.charAt(0));
        System.out.println(str.substring(0, 5));
        System.out.println(str.indexOf("World"));
        System.out.println(str.replace("World", "Java"));
        System.out.println(str.toLowerCase());
        System.out.println(str.toUpperCase());
        System.out.println(str.trim());
        System.out.println(str.equals("Hello, World!"));
        System.out.println(str.equalsIgnoreCase("Hello, World!"));
        System.out.println(str.startsWith("Hello"));
        System.out.println(str.endsWith("World!"));
    }
}